### PR TITLE
Change support nodejs version: update LTS

### PR DESCRIPTION
**Pull request by segayuu**

### CODE REVIEW

**Comment by YoshinoriN** [comment]
We have to decide when drop Node.js v6 support before merge this.
Please see https://github.com/hexojs/hexo/issues/3508

**Comment by YoshinoriN** [comment]
@segayuu 
Btw, how do you think about Node.js 6 support & Hexo v4 roadmap?
IMHO we should discuss about this matter and I want to know your opinion & I would like you to write your opinion to https://github.com/hexojs/hexo/issues/3508.

**Comment by tomap** [comment]
I believe we can proceed with dropping nodejs 6 in this package. (hexo core team) might not be "close" enough to discuss & decide on this subject collectively.

**Comment by YoshinoriN** [comment]
@tomap 
> I believe we can proceed with dropping nodejs 6 in this package. 

Is this mean drop Node.js v6 individually by each package (plugins)?

**Pull request merged**
