### PR TITLE
Switch from Coffee to plain JS

### PR DESCRIPTION
**Pull request by tomap**
Fix build
Update gulp dependencies

### CODE REVIEW

**Comment by akfish** [comment]
Ah. The code I've written at the dawn of the Great JavaScript Fatigue when CoffeeScript was still a thing! 

Please note that hexo-inject shares the exact same build scripts. 
With all the tools we have today, they seems very redundant. I would suggest ditching them all together. Babel and mocha's CLI should be more than enough.

**Comment by YoshinoriN** [comment]
@tomap 

Thank you very much :)
Now, I'm trying this PR in my local machine. But, it has some errors when npm install...

```sh
yoshinorin@hp-spector:/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math$ npm install

> hexo-math@4.0.0 postinstall /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math
> cd ../.. && npm install --save hexo-inject

npm WARN deprecated hexo-inject@1.0.0: The author does not use Hexo any more. This plugin is no longer maintained.
npm WARN saveError ENOENT: no such file or directory, open '/mnt/c/Users/N.Yoshinori/work/development/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/mnt/c/Users/N.Yoshinori/work/development/package.json'
npm WARN development No description
npm WARN development No repository field.
npm WARN development No README data
npm WARN development No license field.

+ hexo-inject@1.0.0
updated 1 package in 1.797s
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> hexo-math@4.0.0 prepublish /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math
> gulp clean && gulp es6

[10:19:50] Using gulpfile /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/gulpfile.js
[10:19:50] Starting 'clean'...
Deleted:
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/consts.js
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/filter/inject.js
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/filter/post.js
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/index.js
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/main.js
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/option.js
/mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/lib/tag/math.js
[10:19:50] Finished 'clean' after 24 ms
[10:19:52] Using gulpfile /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/gulpfile.js
[10:19:52] Starting 'es6'...
begin sourcemaps
end sourcemaps
[10:19:52] Finished 'es6' after 15 ms
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
[10:19:54] Plumber found unhandled error:
 Error in plugin "gulp-babel"
Message:
    Plugin/Preset files are not allowed to export objects, only functions. In /mnt/c/Users/N.Yoshinori/work/development/HEXO/hexo-math/node_modules/babel-preset-es2015/lib/index.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by tomap** [comment]
@YoshinoriN I reproduced those errors, but they are well beyond my understanding of babel. Maybe @akfish or @NoahDragon can help ?

**Comment by akfish** [comment]
I pushed 5889472. Build, test and clean tasks no longer use gulp. 

Build and clean works fine. But I couldn't get the test running. If I remember correctly, the test workflow is like this:
1. `gulp asset:test` (source in `gulp-task/test-asset.js`) clones `https://github.com/hexojs/hexo-starter.git` into `test/site` folder. Runs `npm install` in that folder.
2. `gulp asset:deploy` copies `test/asset` into `test/site`.
3. `mocha` runs tests, which will compile `test/site` with hexo.

The `npm install` in `test/site` failed on my system with:
```
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/akfish/Dev/js/hexo-math/test/site/node_modules/highlight.js/tools/build.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
Besides that, the tests might rely on some hexo internal APIs to work, which could be broken by newer hexo versions.

Other issues need to be resolved are:
* `npm prepublish` is deprecated.
* `hexo-math` depends on `hexo-inject`. But last time I checked, `hexo-inject` must be installed in user's site project for this to work. It won't work if installed as `hexo-math`'s dependency. That's the purpose of the [`npm postinstall` hook](https://github.com/hexojs/hexo-math/blob/master/package.json#L13). But that seems to be broken as well. 
If this `hexo-inject` dependency situation is still the same in current version of hexo, we could consider using npm's `peerDependencies` feature. It would be even better if latest hexo has built-in APIs that are equivalent to `hexo-inject`. 

I haven't been using hexo for years. So my knowledge regarding hexo's internal workings is obviously out of date. That limited my helpfulness on this issue. But I hope this will give you a good starting point.

**Comment by akfish** [comment]
I implemented pretest workflow in native commands. It's now completely gulp free. Good luck!

**Comment by YoshinoriN** [comment]
Thank you very very much ❤️  
I'm going to test it 😄

**Comment by tomap** [comment]
There are two failing tests:
one of the reason is that links in MD are now marked as rel=noopener instead of rel=extenal
I believe this is a change of behavior from hexo or the markdown plugin, not this code

**Comment by tomap** [comment]
And there is also the highlighted code which went from <span> to <div>

**Comment by YoshinoriN** [comment]
@tomap 
I found two pull request about ci error. These changes are correct behavior :)

* https://github.com/hexojs/hexo-util/pull/16
* https://github.com/hexojs/hexo/pull/2820

I think we can merge this PR after fix test case.

**Comment by YoshinoriN** [comment]
I fixed the test cases. It's OK.
Now I'm trying in my local machine but `EISDIR: illegal operation on a directory, read` error apper. Do you have any idead?

```sh
C:\Users\N.Yoshinori\work\development\HEXO\hexo-test>npm install tomap/hexo-math#master
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo-math@4.0.0
added 3 packages from 1 contributor and audited 10221 packages in 7.36s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\N.Yoshinori\work\development\HEXO\hexo-test>hexo server
ERROR Plugin load failed: hexo-math
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
```

**Comment by YoshinoriN** [comment]
OK. I misunderstood. I forgot to execute `build` command at hexo-math project.
I tested this below procedure & confirmed work well in my local environment.

### directory stracture

```
├── hexo-test
└── hexo-math
```

### build hexo-math

```sh
$ npm run build

> hexo-math@4.0.0 build C:\Users\N.Yoshinori\work\development\HEXO\hexo-math
> babel src --out-dir lib

Successfully compiled 7 files with Babel.
```

### install hexo-math (local)

```sh
npm install ../hexo-math
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\N.Yoshinori\work\development\HEXO\hexo-math\node_modules\regexpu-core\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\N.Yoshinori\work\development\HEXO\hexo-math\node_modules\yargs\package.json'
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo-math@4.0.0
added 1 package from 1 contributor in 4.868s
```

After install hexo-math(local)

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "git+https://github.com/hexojs/hexo.git#master",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-math": "file:../hexo-math",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}

```

```sh
hexo-test>hexo server
INFO  [hexo-math] Using engine 'mathjax'
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
```

### Result

It seems works well.

mathjax

**Comment by YoshinoriN** [comment]
@tomap 
You requested review to NoahDragon and akfish.
Do you wanna wait NoahDragon's review? IMHO, We can merge this. How do you think?

**Comment by tomap** [comment]
You can merge. I was just requesting anyone to review. But as you did, it's ok

**Comment by YoshinoriN** [comment]
Merged !!
Thank you very much @akfish for the help :)

**Pull request merged**
