### PR TITLE
Remove babel and mjs

### PR DESCRIPTION
**Pull request by segayuu**

### CODE REVIEW

**Comment by segayuu** [comment]
The travis CI error could not be confirmed locally.
It is possible that the test itself is broken in CI.

**Comment by JLHwung** [comment]
I can reproduce test failure on my machine. The test fixture is highly related to the output of hexo helpers and highlight.js.

Since `hello-world` does not contain any TeX definition, I suggest we rewrite the test and treat it as a hexo smoke test. For example we can test if it generates non-empty fixture.

As long as `tag-escape` and other TeX related test pass, it should be good to go.

Could you enable the skipped `block` and `inline` test?

**Comment by segayuu** [comment]
I don't know how to adapt the review.
If you get an error on this side, you can investigate, but it works in my environment.
OS: win10
Node: 12.8.0
NPM: 6.10.3
Git: 2.22.0.windows.1

**Comment by YoshinoriN** [comment]
@segayuu 
This test failure seems does not occur on native Windows.
But I reproduce it using by WSL.

* Windows 10
* WSL (Ubuntu 18.04.1)
* Node.js v12.3.1
* npm 6.10.2
* git 2.17

Please be careful, npm script might be a failure on native Windows if execute `npm install` once on WSL.

Please delete `node_modules` and re-execute `npm install` on native Windows if you face a npm script failure on native Windows after execute `npm install` on WSL.

**Comment by curbengh** [comment]
> This test failure seems does not occur on native Windows.

Line ending?

**Comment by YoshinoriN** [comment]
Maybe I got it. The test failure caused by `hexo-renderer-marked` version.

The test success on Linux (WSL) if [npm-script preset:clone](https://github.com/hexojs/hexo-math/blob/726aff564e7c04aed3221fc94acf2da0923270ff/package.json#L15) change to following.

```js
"pretest:clone": "git clone --recursive https://github.com/hexojs/hexo-starter.git ./test/site && cd ./test/site && git checkout a4d53738d734b1151576337ea427b6186115943a"
```

The commit hash [a4d53738d734b1151576337ea427b6186115943a](https://github.com/hexojs/hexo-starter/commits/a4d53738d734b1151576337ea427b6186115943a) is parent commit of update [hexo-renderer-marked](https://github.com/hexojs/hexo-starter/commit/cd673dfb44667bc383d14fe0d62d7c08a30eecd1) to v1.0.1

> Line ending difference?

Maybe no. But, I don't know why the test passes on native Windows. That's weird 🤔

**Comment by segayuu** [comment]
Thank @YoshinoriN !

**Comment by curbengh** [comment]
> Maybe I got it. The test failure caused by `hexo-renderer-marked` version.

similar issue with https://github.com/hexojs/hexo/pull/3571?

**Pull request merged**
